.

diff --git a/whonix_shared/usr/lib/whonix/sdw_post_failure b/whonix_shared/usr/lib/whonix/sdw_post_failure
--- a/whonix_shared/usr/lib/whonix/sdw_post_failure
+++ b/whonix_shared/usr/lib/whonix/sdw_post_failure
@@ -1,5 +1,49 @@
 #!/bin/bash
 
-sudo -u user /bin/bash -x /usr/bin/timesync --autostart --cron
+#set -x
 
-exit 0
+NOTIFY_MSG="Running Secure Network Time Synchronization (timesync)...
+This will happen in background and will take approximately 60 seconds.
+
+For better anonymity, please do use the internet in Whonix until timesync succeeded."
+
+ICON="/usr/share/whonix/icons/timesync.ico"
+
+SCRIPTNAME="$(basename $0)"
+IDENTIFIER="timesync"
+
+source /usr/lib/whonix/whonixcheck/help_error-handler
+source /usr/lib/whonix/whonixcheck/help_output
+source /usr/lib/whonix/whonixcheck/10_preparation
+source /usr/lib/whonix/whonixcheck/17_check_tor_enabled
+source /usr/lib/whonix/whonixcheck/67_check_clock
+source /usr/lib/whonix/whonixcheck/70_check-sdwdate
+source /usr/lib/whonix/whonixcheck/75_cleanup
+
+timesync_main() {
+   trap "error_handler" ERR
+
+   RUN_BY_CRON="1"
+
+   preparation ## 10_preparation
+
+   $output ${output_opts[@]} --forget
+
+   if [ "$FUNCTION" = "" ]; then
+      true
+   else
+      $FUNCTION
+      return 0
+   fi
+
+   check_tor_enabled ## 17_check_tor_enabled
+
+   check_bootclockrandomization ## 67_check_clock
+
+   check_timesanitycheck ## 67_check_clock
+
+   #cleanup ## 75_cleanup
+}
+
+timesync_main ${1+"$@"}
+
diff --git a/whonix_shared/usr/lib/whonix/sdw_post_success b/whonix_shared/usr/lib/whonix/sdw_post_success
--- a/whonix_shared/usr/lib/whonix/sdw_post_success
+++ b/whonix_shared/usr/lib/whonix/sdw_post_success
@@ -1,5 +1,56 @@
 #!/bin/bash
 
-sudo -u user /bin/bash -x /usr/bin/timesync --autostart --cron
+#set -x
 
-exit 0
+NOTIFY_MSG="Running Secure Network Time Synchronization (timesync)...
+This will happen in background and will take approximately 60 seconds.
+
+For better anonymity, please do use the internet in Whonix until timesync succeeded."
+
+ICON="/usr/share/whonix/icons/timesync.ico"
+
+SCRIPTNAME="$(basename $0)"
+IDENTIFIER="timesync"
+
+source /usr/lib/whonix/whonixcheck/help_error-handler
+source /usr/lib/whonix/whonixcheck/help_cli
+source /usr/lib/whonix/whonixcheck/help_parse-cmd-options
+source /usr/lib/whonix/whonixcheck/10_preparation
+source /usr/lib/whonix/whonixcheck/16_delete_old_files
+source /usr/lib/whonix/whonixcheck/17_check_tor_enabled
+source /usr/lib/whonix/whonixcheck/30_welcome
+source /usr/lib/whonix/whonixcheck/35_disclaimer
+source /usr/lib/whonix/timesync/30_run-sdwdate
+source /usr/lib/whonix/whonixcheck/67_check_clock
+source /usr/lib/whonix/whonixcheck/70_check-sdwdate
+source /usr/lib/whonix/whonixcheck/75_cleanup
+
+timesync_main() {
+   trap "error_handler" ERR
+
+   parse_cmd_options ${1+"$@"} ## help_parse-cmd-options
+   preparation ## 10_preparation
+
+   ## no $output --forget
+
+   if [ "$FUNCTION" = "" ]; then
+      true
+   else
+      $FUNCTION
+      return 0
+   fi
+
+   ## timesanitycheck
+   run_timesanitycheck ## 70_check-sdwdate
+   
+   check_sdwdate ## 70_check-sdwdate
+
+   /usr/lib/whonix/delay /usr/lib/whonix/output --identifier timesync --icon /usr/share/whonix/icons/timesync.ico --showcli
+   /usr/lib/whonix/delay /usr/lib/whonix/output --identifier timesync --icon /usr/share/whonix/icons/timesync.ico --showx
+
+   cleanup ## 75_cleanup
+}
+
+timesync_main ${1+"$@"}
+
+## End of timesync script.
